import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import Navbar from '../components/Navbar';
import { ShieldCheck, Plus, CheckCircle, Loader2 } from 'lucide-react';

export default function AdminDashboard() {
  const [pendingCampaigns, setPendingCampaigns] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [publishingId, setPublishingId] = useState<string | null>(null);

  // Form states for the offer
  const [offerTitle, setOfferTitle] = useState('');
  const [offerDesc, setOfferDesc] = useState('');
  const [discountValue, setDiscountValue] = useState('');
  const [promoCode, setPromoCode] = useState('');

  useEffect(() => {
    fetchPending();
  }, []);

  const fetchPending = async () => {
    try {
      const res = await api.get('/campaigns/admin/pending');
      setPendingCampaigns(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handlePublish = async (campaignId: string) => {
    setPublishingId(campaignId);
    try {
      await api.post(`/campaigns/admin/${campaignId}/publish-offer`, {
        title: offerTitle || 'Special Partner Offer',
        description: offerDesc || 'Exclusive discount generated by AdVantage.',
        offer_value: discountValue || '10%',
        coupon_code: promoCode || 'SAVE10',
        cta_text: "Claim Offer",
        landing_page_url: "https://example.com"
      });
      // Remove from list
      setPendingCampaigns(prev => prev.filter(c => c.id !== campaignId));
      
      // Reset form
      setOfferTitle('');
      setOfferDesc('');
      setDiscountValue('');
      setPromoCode('');
    } catch (err) {
      console.error(err);
    } finally {
      setPublishingId(null);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-brand-pink animate-spin" />
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <Navbar />
      
      <main className="pt-24 pb-12 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8 flex items-center gap-3">
          <div className="p-3 bg-brand-pink/20 text-brand-pink rounded-xl">
            <ShieldCheck className="w-8 h-8" />
          </div>
          <div>
            <h1 className="text-3xl font-bold">Admin Portal</h1>
            <p className="text-gray-400">Review company requirements and publish live offers.</p>
          </div>
        </div>

        <div className="space-y-8">
          {pendingCampaigns.length === 0 ? (
            <div className="glass p-12 rounded-2xl border border-dark-border text-center">
              <CheckCircle className="w-12 h-12 text-green-500 mx-auto mb-4" />
              <h4 className="text-xl font-medium text-white mb-2">All caught up!</h4>
              <p className="text-gray-400">There are no pending campaign requests from advertisers right now.</p>
            </div>
          ) : (
            pendingCampaigns.map(campaign => (
              <div key={campaign.id} className="glass p-6 rounded-2xl border border-dark-border grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div>
                  <h3 className="text-xl font-bold mb-2">Requested Campaign: {campaign.name}</h3>
                  <p className="text-gray-400 mb-4">{campaign.description}</p>
                  
                  <div className="flex gap-4 mb-4">
                    <div className="bg-white/5 px-4 py-2 rounded-lg">
                      <p className="text-xs text-gray-500">Budget</p>
                      <p className="font-bold text-green-400">${campaign.budget}</p>
                    </div>
                    <div className="bg-white/5 px-4 py-2 rounded-lg">
                      <p className="text-xs text-gray-500">Dates</p>
                      <p className="text-sm">{new Date(campaign.start_date).toLocaleDateString()} - {new Date(campaign.end_date).toLocaleDateString()}</p>
                    </div>
                  </div>
                </div>

                <div className="bg-dark-surface p-6 rounded-xl border border-dark-border">
                  <h4 className="font-bold text-brand-pink mb-4 flex items-center gap-2">
                    <Plus className="w-4 h-4" /> Create Offer for this Campaign
                  </h4>
                  
                  <div className="space-y-4">
                    <input
                      type="text"
                      value={offerTitle}
                      onChange={e => setOfferTitle(e.target.value)}
                      placeholder="Offer Title (e.g. Summer Sale 20%)"
                      className="w-full px-4 py-2 bg-dark-base border border-dark-border rounded-lg text-sm"
                    />
                    <textarea
                      value={offerDesc}
                      onChange={e => setOfferDesc(e.target.value)}
                      placeholder="Offer Description"
                      className="w-full px-4 py-2 bg-dark-base border border-dark-border rounded-lg text-sm h-20"
                    />
                    <div className="flex gap-4">
                      <input
                        type="number"
                        value={discountValue}
                        onChange={e => setDiscountValue(e.target.value)}
                        placeholder="Discount %"
                        className="w-1/2 px-4 py-2 bg-dark-base border border-dark-border rounded-lg text-sm"
                      />
                      <input
                        type="text"
                        value={promoCode}
                        onChange={e => setPromoCode(e.target.value)}
                        placeholder="PROMOCODE"
                        className="w-1/2 px-4 py-2 bg-dark-base border border-dark-border rounded-lg text-sm uppercase"
                      />
                    </div>
                    
                    <button
                      onClick={() => handlePublish(campaign.id)}
                      disabled={publishingId === campaign.id}
                      className="w-full py-2 bg-brand-pink hover:bg-brand-purple transition-colors text-white font-medium rounded-lg flex justify-center items-center gap-2"
                    >
                      {publishingId === campaign.id ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Publish Live to Marketplace'}
                    </button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </main>
    </div>
  );
}
